// src/pages/api/openai-token.js
import { getMasterRuleBook, POLICY_VERSION } from "../../lib/ruleBook";
import { withApiLogger } from "../../lib/apiMiddleware";
import { db } from "../../lib/firebase";
import { ref, get } from "firebase/database";

// --- SECURITY: Rate Limiting ---
const rateLimitMap = new Map();
const RATE_LIMIT_WINDOW_MS = 60000;
const MAX_TOKEN_REQUESTS = 5; // Strict limit: max 5 WebRTC connections per minute per IP

// --- SECURITY: Payload Validation ---
// Ensures session_id strictly matches the format generated by the frontend: "lead_{timestamp}_{randomHash}"
// Prevents Firebase path traversal attacks (e.g. session_id: "../../admin_keys")
const isValidSessionId = (id) => /^lead_\d+_[a-z0-9]{5,10}$/i.test(id);

function generateHash(str) {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 33) ^ str.charCodeAt(i);
  }
  return (hash >>> 0).toString(16);
}

async function handler(req, res, apiLogger) {
  if (req.method !== "POST")
    return res.status(405).json({ error: "Method not allowed" });

  try {
    const { session_id, retrievedKnowledge = "" } = req.body || {};

    if (!session_id || !isValidSessionId(session_id)) {
      return res.status(400).json({ error: "A valid session_id is required." });
    }

    // --- SECURITY: Enforce Rate Limits ---
    const clientIp =
      req.headers["x-forwarded-for"] ||
      req.socket?.remoteAddress ||
      "unknown_ip";
    const rateKey = `${clientIp}_${session_id}`;
    const now = Date.now();
    const userRateData = rateLimitMap.get(rateKey) || {
      count: 0,
      firstRequest: now,
    };

    if (now - userRateData.firstRequest > RATE_LIMIT_WINDOW_MS) {
      userRateData.count = 1;
      userRateData.firstRequest = now;
    } else {
      userRateData.count++;
      if (userRateData.count > MAX_TOKEN_REQUESTS) {
        apiLogger.warn(
          `[SECURITY] Voice Token rate limit exceeded for ${rateKey}`,
        );
        return res.status(429).json({
          error: "Too many connection attempts. Please wait a moment.",
        });
      }
    }
    rateLimitMap.set(rateKey, userRateData);

    let serverContext = {};
    let privacyPatch = [];
    let factualSummary = "No prior conversation.";

    try {
      const prospectSnap = await get(ref(db, `prospects/${session_id}`));
      if (prospectSnap.exists()) {
        const prospectData = prospectSnap.val();
        serverContext = prospectData.context_patch || {};
        privacyPatch = prospectData.privacy_patch || [];
        if (prospectData.factual_summary) {
          factualSummary = prospectData.factual_summary;
        }
      }
    } catch (dbErr) {
      apiLogger.error("Firebase read error during voice init:", dbErr);
    }

    const { instructions, botConfig } = await getMasterRuleBook(
      "voice",
      serverContext,
      retrievedKnowledge,
    );

    // --- HARD ROLLBACK GATE ---
    if (botConfig.voiceEnabled === false) {
      return res.status(403).json({
        error:
          "Voice features have been disabled by the administrator. Please use the text chat.",
      });
    }

    const sessionVersions = {
      policy: POLICY_VERSION,
      config_snapshot: generateHash(JSON.stringify(botConfig)),
      knowledge: retrievedKnowledge ? generateHash(retrievedKnowledge) : "none",
    };

    const sessionSpecificInstructions = `${instructions}
    
    EXISTING SESSION CONTEXT:
    Factual Summary: ${factualSummary}
    Explicitly Refused Fields: ${privacyPatch.length > 0 ? privacyPatch.join(", ") : "None"}
    
    TOOL CALLING PROTOCOL (CRITICAL):
    1. IMMEDIATE EXECUTION: If a user asks for a human, callback, or audit, IMMEDIATELY call the appropriate tool. 
    2. PRIVACY REFUSALS: If a user declines to provide detail, log it with 'record_privacy_preference'.
    3. DATA DELETION: If a user asks to delete their data, erase history, or forget them, IMMEDIATELY invoke the 'request_data_deletion' tool.`;

    const sessionConfig = {
      session: {
        type: "realtime",
        prompt: {
          id: "pmpt_6a7367d873788195bf7a4e09952104ef0d096b48f283d3cf",
          version: "3",
        },
        instructions: sessionSpecificInstructions,
        audio: {
          input: {
            format: { type: "audio/pcm", rate: 24000 },
            transcription: { model: "whisper-1" },
            noise_reduction: { type: "far_field" },
            turn_detection: botConfig.turnDetection,
          },
          output: {
            format: { type: "audio/pcm", rate: 24000 },
            voice: botConfig.voice || "ash",
          },
        },
        output_modalities: ["audio"],
        tools: [
          {
            type: "function",
            name: "update_prospect_context",
            description:
              "Silently update background context about the user's business and contact info.",
            parameters: {
              type: "object",
              properties: {
                contact_info: {
                  type: "object",
                  properties: {
                    name: { type: "string" },
                    email: { type: "string" },
                    phone: { type: "string" },
                  },
                },
                business_context: {
                  type: "object",
                  properties: {
                    industry: { type: "string" },
                    business_problem: { type: "string" },
                  },
                },
              },
            },
          },
          {
            type: "function",
            name: "request_website_audit",
            description: "Submit a website URL for a free audit.",
            parameters: {
              type: "object",
              properties: {
                website_url: { type: "string" },
                email: { type: "string" },
              },
              required: ["website_url"],
            },
          },
          {
            type: "function",
            name: "request_consultation",
            description: "Request to book a demo or consultation.",
            parameters: {
              type: "object",
              properties: {
                preferred_date: { type: "string" },
                preferred_time: { type: "string" },
              },
            },
          },
          {
            type: "function",
            name: "request_callback",
            description: "Submit a request for the team to call the user back.",
            parameters: {
              type: "object",
              properties: { phone_number: { type: "string" } },
              required: ["phone_number"],
            },
          },
          {
            type: "function",
            name: "request_human_handoff",
            description: "Escalate the conversation to a live human agent.",
            parameters: {
              type: "object",
              properties: { reason: { type: "string" } },
            },
          },
          {
            type: "function",
            name: "record_privacy_preference",
            description:
              "Record if a user explicitly refuses to provide certain data.",
            parameters: {
              type: "object",
              properties: {
                refused_fields: { type: "array", items: { type: "string" } },
              },
            },
          },
          {
            type: "function",
            name: "request_data_deletion",
            description:
              "Permanently delete the user's personal data and voice transcripts from the system.",
            parameters: { type: "object", properties: {} },
          },
        ],
        max_output_tokens: "inf",
        reasoning: { effort: "low" },
      },
    };

    // --- SECURITY: Internal API Key Mapping ---
    // The browser never receives this key. It only receives the short-lived WebRTC Client Secret in the response.
    const response = await fetch(
      "https://api.openai.com/v1/realtime/client_secrets",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(sessionConfig),
      },
    );

    const data = await response.json();
    if (!response.ok)
      return res.status(response.status).json({ error: data.error?.message });

    res.status(200).json({ ...data, versions: sessionVersions });
  } catch (error) {
    apiLogger.error("Token Generation Failure:", error);
    res.status(500).json({ error: "Failed to generate session token" });
  }
}

export default withApiLogger(handler, "Voice-Agent-API");
